# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Pods for ios
  pod 'Dip'
  pod 'IQKeyboardManagerSwift'
end
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end
